/**
 * AI Insights Component
 * AI-powered market analysis and recommendations
 */

import { AlertTriangle, Brain, CheckCircle, TrendingUp, Zap } from 'lucide-react';
import React from 'react';

const Insights: React.FC = () => {
    const insights = [
        {
            id: 1,
            type: 'bullish',
            icon: TrendingUp,
            title: 'Bitcoin Showing Strong Support',
            confidence: 85,
            analysis: 'Technical indicators suggest Bitcoin is finding strong support at current levels with potential for upward movement.',
            recommendation: 'Consider dollar-cost averaging into BTC over the next 2-3 weeks.',
            timeframe: '2-4 weeks',
        },
        {
            id: 2,
            type: 'neutral',
            icon: AlertTriangle,
            title: 'Gold Market Consolidation',
            confidence: 72,
            analysis: 'Gold prices are consolidating in a narrow range. Economic indicators suggest mixed signals for precious metals.',
            recommendation: 'Monitor Federal Reserve policy announcements for directional clarity.',
            timeframe: '1-2 weeks',
        },
        {
            id: 3,
            type: 'opportunity',
            icon: CheckCircle,
            title: 'Ethereum Network Upgrades',
            confidence: 90,
            analysis: 'Upcoming network improvements could positively impact ETH value through reduced transaction costs and increased utility.',
            recommendation: 'Educational opportunity to learn about blockchain technology upgrades.',
            timeframe: '3-6 months',
        },
    ];

    const getTypeColor = (type: string) => {
        switch (type) {
            case 'bullish': return '#28A745';
            case 'bearish': return '#DC3545';
            case 'neutral': return '#FFC107';
            case 'opportunity': return '#17A2B8';
            default: return '#6C757D';
        }
    };

    const getTypeEmoji = (type: string) => {
        switch (type) {
            case 'bullish': return '🚀';
            case 'bearish': return '🔻';
            case 'neutral': return '⚖️';
            case 'opportunity': return '💡';
            default: return '📊';
        }
    };

    return (
        <div className="insights-page">
            <div className="insights-header">
                <Brain size={48} className="header-icon" />
                <div className="header-content">
                    <h1>AI Market Insights</h1>
                    <p>Powered by advanced market analysis algorithms</p>
                </div>
            </div>

            <div className="insights-disclaimer">
                <div className="disclaimer-content">
                    <Zap className="disclaimer-icon" />
                    <div>
                        <h3>🤖 AI-Generated Analysis</h3>
                        <p>These insights are generated by AI for educational purposes only. Not financial advice. Always conduct your own research and consult professionals.</p>
                    </div>
                </div>
            </div>

            <div className="insights-grid">
                {insights.map((insight) => {
                    const IconComponent = insight.icon;
                    return (
                        <div key={insight.id} className="insight-card">
                            <div className="insight-header">
                                <div className="insight-type">
                                    <span
                                        className="type-badge"
                                        style={{ backgroundColor: getTypeColor(insight.type) }}
                                    >
                                        {getTypeEmoji(insight.type)} {insight.type}
                                    </span>
                                </div>
                                <div className="insight-confidence">
                                    <span>Confidence: {insight.confidence}%</span>
                                    <div className="confidence-bar">
                                        <div
                                            className="confidence-fill"
                                            style={{
                                                width: `${insight.confidence}%`,
                                                backgroundColor: getTypeColor(insight.type)
                                            }}
                                        ></div>
                                    </div>
                                </div>
                            </div>

                            <div className="insight-content">
                                <div className="insight-title">
                                    <IconComponent size={20} />
                                    <h3>{insight.title}</h3>
                                </div>

                                <div className="insight-analysis">
                                    <h4>Analysis</h4>
                                    <p>{insight.analysis}</p>
                                </div>

                                <div className="insight-recommendation">
                                    <h4>Educational Note</h4>
                                    <p>{insight.recommendation}</p>
                                </div>

                                <div className="insight-meta">
                                    <span className="timeframe">Timeframe: {insight.timeframe}</span>
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>

            <div className="insights-coming-soon">
                <Brain size={48} />
                <h2>Enhanced AI Features Coming Soon</h2>
                <div className="upcoming-features">
                    <div className="feature-item">
                        <CheckCircle size={16} />
                        <span>Personalized portfolio recommendations</span>
                    </div>
                    <div className="feature-item">
                        <CheckCircle size={16} />
                        <span>Risk assessment analysis</span>
                    </div>
                    <div className="feature-item">
                        <CheckCircle size={16} />
                        <span>Market sentiment tracking</span>
                    </div>
                    <div className="feature-item">
                        <CheckCircle size={16} />
                        <span>Real-time news impact analysis</span>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Insights;
